import { v4 as uuid } from "uuid";
export interface IServciesData {
  id: string;
  title: string;
  items: string[];
}

export const SERVICES = {
  en: [
    {
      id: uuid(),
      title: "COMMERCIAL AND CORPORATE LAW",
      items: [
        "Represent in litigation, enforcement and other proceedings in the area of commercial law in front of courts and other competent authorities",
        "Consulting on contract drafting in the area of commercial and corporate law",
        "Incorporation of companies and other entities",
        "Mergers and acquisitions and other corporate changes",
        "Legal due diligence",
        "Pre-bankruptcy settlement, insolvency and liquidation",
        "Advising and assisting companies in various legal matters",
      ],
    },
    {
      id: uuid(),
      title: "BANKING, FINANCE AND CAPITAL MARKETS",
      items: [
        "Banking and financial regulation",
        "Capital markets offerings",
        "Corporate finance",
        "Investment funds",
        "Private equity",
        "Project finance",
        "Securities regulation",
        "Security and guarantees",
        "Structured finance",
        "Sale and Purchase of Non-performing loans",
        "Initial public offerings",
        "Listings",
        "Prospectus",
        "Representation at Croatian Financial Supervisory Agency (HANFA)",
      ],
    },
    {
      id: uuid(),
      title: "DEBT COLLECTION",
      items: [
        "Consulting on collateral and collection on receivables",
        "Examination of the creditworthiness of the counterparty",
        "Drafting payment instruments",
        "Representation in enforcement and litigation proceedings for the collection of receivables",
      ],
    },
    {
      id: uuid(),
      title: "DISPUTE RESOLUTION",
      items: [
        "Representation before courts",
        "Representation before other bodies and agencies",
        "Domestic and international arbitration",
        "Alternative dispute resolution",
      ],
    },
    {
      id: uuid(),
      title: "PROPERTY AND LAND REGISTRY LAW",
      items: [
        "Sales-purchase agreements, gift deeds and other types of ownership transfers of movable and immovable property",
        "Real estate and movables lease agreements (apartments, business premises, land)",
        "Advising and representing clients in proceedings regarding the protection of property, ownership and other rights",
        "Representing clients in land registry and cadastral proceedings",
        "Obtaining permits and licences (approval for use and building permit, energy certificate)",
        "Conducting individual correction procedures",
        "Representing clients in expropriation proceedings",
        "Construction and Architectural Agreements",
        "Legal Due Diligence",
        "Hotel Industry and Hospitality",
      ],
    },
    {
      id: uuid(),
      title:
        "PERSONAL DATA PROTECTION (GENERAL DATA PROTECTION REGULATION – GDPR)",
      items: [
        "Identifying business processes which include personal data processing, risk assessment and advising on the necessary alignment measures",
        "Drafting and alignment of data subjects’ consent forms for personal data processing adjusted for various purposes",
        "Drafting and alignment of privacy notices with content adjusted for different categories of data subjects (such as workers, suppliers, clients)",
        "Drafting and alignment of contracts with personal data processors as well as data protection clauses in contracts with other recipients of personal data",
        "Drafting and alignment of records of processing activities",
        "Advising and assistance with the preparation of data protection impact assessments",
        "Drafting and alignment of internal documents with respect to personal data protection",
      ],
    },
    {
      id: uuid(),
      title: "INTELLECTUAL PROPERTY",
      items: [
        "Trademark, ",
        "Patent and Design Searches and Checks, ",
        "Licensing Agreements,",
        "Copyrights",
      ],
    },
    {
      id: uuid(),
      title: "EMPLOYMENT",
      items: [
        "Employment contracts, contracts with management and board members",
        "Incentive schemes",
        "Competition and nondisclosure agreements",
        "Discrimination and harassment",
        "Immigration and mobility",
        "Pensions and employee benefits",
        "Employment of foreigners",
        "Employment Bylaws",
        "Health and safety at work",
        "Data protection",
        "Employment termination",
        "Redundancy schemes",
        "Employment litigation",
        "Whistle-blowing",
      ],
    },
    {
      id: uuid(),
      title: "COMPETITION LAW",
      items: [
        "Concentration assessments and notifications",
        "Prohibited agreements, block and individual exemptions",
        "Dominant position and restrictive practices",
        "Representation before regulators",
      ],
    },
  ],
  hr: [
    {
      id: uuid(),
      title: "TRGOVAČKO PRAVO I PRAVO DRUŠTAVA",
      items: [
        "Zastupanje u parničnim, ovršnim i drugim postupcima u području trgovačkog prava pred sudovima i drugim nadležnim tijelima",
        "Pravno savjetovanje i izrada ugovora iz područja trgovačkog prava i prava društava",
        "Osnivanje trgovačkih društava i drugih pravnih osoba",
        "Spajanje i pripajanje društava te druge statusne promjene",
        "Pravni due diligence trgovačkih društava",
        "Predstečajna nagodba, stečaj i likvidacija",
        "Pravno savjetovanje i pružanje cjelovite pravne pomoći i podrške trgovačkim društvima",
      ],
    },
    {
      id: uuid(),
      title: "BANKARSTVO, FINANCIJE I TRŽIŠTA KAPITALA",
      items: [
        "Bankarski i financijski propisi",
        "Ponude na tržištu kapitala",
        "Korporativne financije",
        "Investicijski fondovi",
        "Privatni vlasnički kapital",
        "Projektno financiranje",
        "Propisi o vrijednosnim papirima",
        "Sredstva osiguranja i garancije",
        "Strukturirano financiranje",
        "Prodaja i kupnja neprihodonosnih kredita (NPL)",
        "Inicijalna javna ponuda",
        "Uvrštenja vrijednosnih papira na burzu",
        "Izrada prospekta",
        "Zastupanje pred HANFA-om",
      ],
    },
    {
      id: uuid(),
      title: "NAPLATA POTRAŽIVANJA",
      items: [
        "Savjetovanja pri osiguranju i naplati potraživanja",
        "Ispitivanje boniteta protustranke",
        "Sastavljanje instrumenata plaćanja",
        "Zastupanje u ovršnim i parničnim postupcima radi naplate potraživanja",
      ],
    },
    {
      id: uuid(),
      title: "RJEŠAVANJE SPOROVA",
      items: [
        "Zastupanje pred sudovima",
        "Zastupanje pred drugim nadležnim tijelima",
        "Domaća i međunarodna arbitraža",
        "Alternativno rješavanje sporova",
      ],
    },
    {
      id: uuid(),
      title: "STVARNO I ZEMLJIŠNOKNJIŽNO PRAVO",
      items: [
        "Ugovori o kupoprodaji, darovanju i drugim vrstama prijenosa vlasništva na nekretninama i pokretninama",
        "Ugovori o najmu i zakupu nekretnina (stanova, poslovnih prostora, zemljišta) te pokretnina",
        "Pravno savjetovanje i zastupanje u postupcima radi zaštite posjeda, vlasništva i drugih stvarnih prava pred sudovima i drugim tijelima",
        "Zastupanje u postupcima upisa vlasništva i drugih prava u zemljišne knjige (uknjižbe, predbilježbe, zabilježbe)",
        "Ishođenje dozvola i odobrenja (uporabna i građevinska dozvola, energetski certifikati)",
        "Uređenje zemljišnoknjižnog i katastarskog stanja te provođenje pojedinačnog zemljišnoknjižnog ispravnog postupka",
        "Zastupanje u postupcima izvlaštenja",
        "Ugovori o građenju",
        "Pravni due diligence",
        "Savjetovanje za ulaganje u hotele i razvojne turističke projekte",
      ],
    },
    {
      id: uuid(),
      title: "ZAŠTITA OSOBNIH PODATAKA (OPĆA UREDBA O ZAŠTITI PODATAKA – GDPR)",
      items: [
        "Identifikacija poslovnih procesa koji uključuju obradu osobnih podataka, procjena rizika te savjetovanje o potrebnim mjerama usklađenja",
        "Sastavljanje ili usklađivanje privola ispitanika za obradu osobnih podataka prilagođenih za različite svrhe obrade",
        "Sastavljanje ili usklađivanje obavijesti o privatnosti (tzv. privacy notice) s prilagođenim sadržajem za različite kategorije ispitanika (npr. radnike, dobavljače, klijente)",
        "Sastavljanje ili usklađivanje ugovora s izvršiteljima obrade odnosno klauzula o zaštiti osobnih podataka u ugovorima s drugim primateljima osobnih podataka",
        "Sastavljanje ili usklađivanje evidencija aktivnosti obrade",
        "Savjetovanje o potrebi izrade te pomoć prilikom izrade procjene učinka na zaštitu osobnih podataka",
        "Sastavljanje ili usklađivanje internih akata u vezi sa zaštitom osobnih podataka",
      ],
    },
    {
      id: uuid(),
      title: "PRAVO INTELEKTUALNOG VLASNIŠTVA",
      items: [
        "Registracija žiga, patenata i industrijskog dizajna",
        "Pretrage žiga, patenata i industrijskog dizajna",
        "Ugovori o licenci ",
        "Autorska prava",
      ],
    },
    {
      id: uuid(),
      title: "RADNO PRAVO",
      items: [
        "Ugovori o radu, ugovori s menadžerima i članovima uprave",
        "Politika bonusa",
        "Tržišno natjecanje i ugovori o povjerljivosti podataka",
        "Diskriminacija i uznemiravanje",
        "Imigracija i mobilnost",
        "Mirovine i povlastice za zaposlenike",
        "Zapošljavanje stranaca",
        "Pravilnici o radu",
        "Zaštita na radu",
        "Zaštita podataka",
        "Otkazivanje ugovora o radu",
        "Zbrinjavanje viška zaposlenika",
        "Zastupanje u radnim sporovima",
        "Zviždači",
      ],
    },
    {
      id: uuid(),
      title: "TRŽIŠNO NATJECANJE",
      items: [
        "Procjene i prijave koncentracija",
        "Zabranjeni sporazumi, skupna i pojedinačna izuzeća",
        "Vladajući položaj i ograničavajuća djelovanja",
        "Zastupanje pred regulatornim tijelom",
      ],
    },
  ],
};
